[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sol_airdrop = "T7vzu9V9N5mrto56wDGZTAX84m5c9tepSzbhyJeycrm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/deepak/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
